// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api_portaria.ContextBase;

#nullable disable

namespace api_portaria.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230928134919_SecondMigration")]
    partial class SecondMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api_portaria.Model.EntradaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cliente")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataHoraEntrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataHoraSaida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TempoParaAtendimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Transportadora")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("tab_entrada");
                });

            modelBuilder.Entity("api_portaria.Model.PrimeiroResponsavelEntradaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EntradaId")
                        .HasColumnType("integer");

                    b.Property<int?>("ResponsavelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EntradaId")
                        .IsUnique();

                    b.HasIndex("ResponsavelId");

                    b.ToTable("tab_PrimeiroResponsavelEntrada");
                });

            modelBuilder.Entity("api_portaria.Model.ResponsavelModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("tab_responsavel");
                });

            modelBuilder.Entity("api_portaria.Model.SegundoResponsavelEntradaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EntradaId")
                        .HasColumnType("integer");

                    b.Property<int?>("ResponsavelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EntradaId")
                        .IsUnique();

                    b.HasIndex("ResponsavelId");

                    b.ToTable("tab_SegundoResponsavelEntrada");
                });

            modelBuilder.Entity("api_portaria.Model.PrimeiroResponsavelEntradaModel", b =>
                {
                    b.HasOne("api_portaria.Model.EntradaModel", "Entrada")
                        .WithOne("PrimeiroResponsavel")
                        .HasForeignKey("api_portaria.Model.PrimeiroResponsavelEntradaModel", "EntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api_portaria.Model.ResponsavelModel", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId");

                    b.Navigation("Entrada");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("api_portaria.Model.SegundoResponsavelEntradaModel", b =>
                {
                    b.HasOne("api_portaria.Model.EntradaModel", "Entrada")
                        .WithOne("SegundoResponsavel")
                        .HasForeignKey("api_portaria.Model.SegundoResponsavelEntradaModel", "EntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api_portaria.Model.ResponsavelModel", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId");

                    b.Navigation("Entrada");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("api_portaria.Model.EntradaModel", b =>
                {
                    b.Navigation("PrimeiroResponsavel");

                    b.Navigation("SegundoResponsavel");
                });
#pragma warning restore 612, 618
        }
    }
}
